version: '3.7'
services:
  database:
    image: postgres:15-alpine
    restart: always
    container_name: eshop_db
    environment:
      - POSTGRES_USER=zimaluk1
      - POSTGRES_PASSWORD=tjv
      - POSTGRES_DB=eshop_db
    ports:
      - '5432:5432'
    volumes:
      - .docker/postgres-data:/var/lib/postgresql/data
  #app:
   # image: eshop
   # depends_on:
   #   - database
   # ports:
   #   - '8080:8080'
   # environment:
    #  SPRING_DATASOURCE_URL: jdbc:postgresql://eshop_db/eshop_db
    #  SPRING_DATASOURCE_USERNAME: zimaluk1
    #  SPRING_DATASOURCE_PASSWORD: tjv
    #  SPRING_JPA_HIBERNATE_DDL_AUTO: update
